

def start():
	start_urls=[
	'http://www.99acres.com/search/property/rent/residential-all/gurgaon?search_type=QS&search_location=CP1&lstAcn=CP_R&lstAcnId=1&src=CLUSTER&preference=R&selected_tab=4&city=8&res_com=R&property_type=R&isvoicesearch=N&keyword_suggest=gurgaon%3B&class=A%2CO%2CB&fullSelectedSuggestions=gurgaon&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiZ3VyZ2FvbiIsIkNJVFlfOCwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=gur&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_8%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1',

	'http://www.99acres.com/search/property/rent/residential-all/delhi-ncr-all?search_type=QS&search_location=CP1&lstAcn=CP_R&lstAcnId=1&src=CLUSTER&preference=R&selected_tab=4&city=1&res_com=R&property_type=R&isvoicesearch=N&keyword_suggest=delhi%20%2F%20ncr%20(all)%3B&class=A%2CO%2CB&fullSelectedSuggestions=delhi%20%2F%20ncr%20(all)&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiZGVsaGkgLyBuY3IgKGFsbCkiLCJDSVRZXzEsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Delhi&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_1%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/bangalore-all?search_type=QS&search_location=CP1&lstAcn=CP_R&lstAcnId=1&src=CLUSTER&preference=R&selected_tab=4&city=20&res_com=R&property_type=R&isvoicesearch=N&keyword_suggest=bangalore%20(all)%3B&class=A%2CO%2CB&fullSelectedSuggestions=bangalore%20(all)&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiYmFuZ2Fsb3JlIChhbGwpIiwiQ0lUWV8yMCwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=Ban&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_20%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/hyderabad-all?search_type=QS&search_location=CP20&lstAcn=CP_R&lstAcnId=20&src=CLUSTER&preference=R&selected_tab=4&city=38&res_com=R&property_type=R&isvoicesearch=N&keyword_suggest=hyderabad%20(all)%3B&class=A%2CO%2CB&fullSelectedSuggestions=hyderabad%20(all)&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiaHlkZXJhYmFkIChhbGwpIiwiQ0lUWV8zOCwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=Hyderabad&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_38%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/kolkata-all?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3127491682826409&src=CLUSTER&preference=R&city=25&res_com=R&class=B%2CO%2CA&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=kolkata%20(all)%3B&fullSelectedSuggestions=kolkata%20(all)&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsia29sa2F0YSAoYWxsKSIsIkNJVFlfMjUsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Kolkata&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_25%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/chandigarh?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3127635937802100&src=CLUSTER&preference=R&city=73&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=chandigarh%3B&fullSelectedSuggestions=chandigarh&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiY2hhbmRpZ2FyaCIsIkNJVFlfNzMsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Chandigarh&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_73%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/nagpur?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3128072276040571&src=CLUSTER&preference=R&city=150&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=nagpur%3B&fullSelectedSuggestions=nagpur&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsibmFncHVyIiwiQ0lUWV8xNTAsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Nag&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_150%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/coimbatore?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3127842619701624&src=CLUSTER&preference=R&city=185&res_com=R&class=B%2CO%2CA&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=coimbatore%3B&fullSelectedSuggestions=coimbatore&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiY29pbWJhdG9yZSIsIkNJVFlfMTg1LCBQUkVGRVJFTkNFX1IsIFJFU0NPTV9SIl19XQ%3D%3D&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=i&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/indore?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3127860277421670&src=CLUSTER&preference=R&city=142&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=indore%3B&fullSelectedSuggestions=indore&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiaW5kb3JlIiwiQ0lUWV8xNDIsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Indore&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_142%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/lucknow?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3127999167712407&src=CLUSTER&preference=R&city=205&res_com=R&class=B%2CO%2CA&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=lucknow%3B&fullSelectedSuggestions=lucknow&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsibHVja25vdyIsIkNJVFlfMjA1LCBQUkVGRVJFTkNFX1IsIFJFU0NPTV9SIl19XQ%3D%3D&texttypedtillsuggestion=Luck&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_205%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/vadodara?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3125814633056129&src=CLUSTER&preference=R&city=96&res_com=R&class=B%2CO%2CA&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=vadodara%3B&fullSelectedSuggestions=vadodara&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsidmFkb2RhcmEiLCJDSVRZXzk2LCBQUkVGRVJFTkNFX1IsIFJFU0NPTV9SIl19XQ%3D%3D&texttypedtillsuggestion=Vadod&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_96%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/patna?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3128272299258490&src=CLUSTER&preference=R&city=71&res_com=R&class=B%2CO%2CA&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=patna%3B&fullSelectedSuggestions=patna&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsicGF0bmEiLCJDSVRZXzcxLCBQUkVGRVJFTkNFX1IsIFJFU0NPTV9SIl19XQ%3D%3D&texttypedtillsuggestion=Patna&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_71%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/bhopal?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3128308443098486&src=CLUSTER&preference=R&city=140&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=bhopal%3B&fullSelectedSuggestions=bhopal&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiYmhvcGFsIiwiQ0lUWV8xNDAsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Bhopal&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_140%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/kanpur?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3128370072007501&src=CLUSTER&preference=R&city=204&res_com=R&class=B%2CO%2CA&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=kanpur%3B&fullSelectedSuggestions=kanpur&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsia2FucHVyIiwiQ0lUWV8yMDQsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Kanpur&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_204%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/vijayawada?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3128464523883138&src=CLUSTER&preference=R&city=61&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=vijayawada%3B&fullSelectedSuggestions=vijayawada&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsidmlqYXlhd2FkYSIsIkNJVFlfNjEsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=vijyawada&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_61%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/ranchi?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3131774116221830&src=CLUSTER&preference=R&city=117&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=ranchi%3B&fullSelectedSuggestions=ranchi&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsicmFuY2hpIiwiQ0lUWV8xMTcsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=ranchi&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_117%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/mangalore?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3133712863861709&src=CLUSTER&preference=R&city=125&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=mangalore%3B&fullSelectedSuggestions=mangalore&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsibWFuZ2Fsb3JlIiwiQ0lUWV8xMjUsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=man&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_125%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/mumbai?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3133757673679551&src=CLUSTER&preference=R&city=12&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword=mumbai&strEntityMap=IiI%3D&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/chennai-all?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3134508154019636&src=CLUSTER&preference=R&city=32&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=chennai%20%28all%29%3B&fullSelectedSuggestions=chennai%20%28all%29&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiY2hlbm5haSAoYWxsKSIsIkNJVFlfMzIsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=chennai&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_32%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/pune?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3134552525191717&src=CLUSTER&preference=R&city=19&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=pune%3B&fullSelectedSuggestions=pune&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsicHVuZSIsIkNJVFlfMTksIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Pune&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_19%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/ahmedabad-all?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3134607513379878&src=CLUSTER&preference=R&city=45&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=ahmedabad%20%28all%29%3B&fullSelectedSuggestions=ahmedabad%20%28all%29&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiYWhtZWRhYmFkIChhbGwpIiwiQ0lUWV80NSwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=Ahm&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_45%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/jaipur?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3134667452134134&src=CLUSTER&preference=R&city=177&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword=jaipur&strEntityMap=IiI%3D&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/bhubaneswar?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3134776009024795&src=CLUSTER&preference=R&city=162&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=bhubaneswar%3B&fullSelectedSuggestions=bhubaneswar&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiYmh1YmFuZXN3YXIiLCJDSVRZXzE2MiwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=Bhu&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_162%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/goa?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3134816096938107&src=CLUSTER&preference=R&city=233&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=goa%3B&fullSelectedSuggestions=goa&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiZ29hIiwiQ0lUWV8yMzMsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=Goa&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_233%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/kerala?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135075939511947&src=CLUSTER&preference=R&city=238&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=kerala%3B&fullSelectedSuggestions=kerala&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsia2VyYWxhIiwiQ0lUWV8yMzgsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&searchform=1&price_min=null&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/surat?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135443468567340&src=CLUSTER&preference=R&city=95&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=surat%3B&fullSelectedSuggestions=surat&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsic3VyYXQiLCJDSVRZXzk1LCBQUkVGRVJFTkNFX1IsIFJFU0NPTV9SIl19XQ%3D%3D&texttypedtillsuggestion=surat&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_95%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/dehradun?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135500845540853&src=CLUSTER&preference=R&city=211&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=dehradun%3B&fullSelectedSuggestions=dehradun&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsiZGVocmFkdW4iLCJDSVRZXzIxMSwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=deh&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_211%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/nasik?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135561632926372&src=CLUSTER&preference=R&city=151&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=nasik%3B&fullSelectedSuggestions=nasik&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsibmFzaWsiLCJDSVRZXzE1MSwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=nasik&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_151%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/vishakhapatnam?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135599857799477&src=CLUSTER&preference=R&city=62&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=vishakhapatnam%3B&fullSelectedSuggestions=vishakhapatnam&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsidmlzaGFraGFwYXRuYW0iLCJDSVRZXzYyLCBQUkVGRVJFTkNFX1IsIFJFU0NPTV9SIl19XQ%3D%3D&texttypedtillsuggestion=visha&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_62%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/varanasi?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135659499895262&src=CLUSTER&preference=R&city=209&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=varanasi%3B&fullSelectedSuggestions=varanasi&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsidmFyYW5hc2kiLCJDSVRZXzIwOSwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=vara&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_209%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/mysore?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135693305278930&src=CLUSTER&preference=R&city=126&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=mysore%3B&fullSelectedSuggestions=mysore&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsibXlzb3JlIiwiQ0lUWV8xMjYsIFBSRUZFUkVOQ0VfUiwgUkVTQ09NX1IiXX1d&texttypedtillsuggestion=mysore&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_126%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null',
	
	'http://www.99acres.com/search/property/rent/residential-all/raipur?search_type=QS&search_location=SH&lstAcn=SEARCH&lstAcnId=3135731078740616&src=CLUSTER&preference=R&city=75&res_com=R&class=A%2CO%2CB&property_type=R&selected_tab=4&isvoicesearch=N&keyword_suggest=raipur%3B&fullSelectedSuggestions=raipur&strEntityMap=W3sidHlwZSI6ImNpdHkifSx7IjEiOlsicmFpcHVyIiwiQ0lUWV83NSwgUFJFRkVSRU5DRV9SLCBSRVNDT01fUiJdfV0%3D&texttypedtillsuggestion=raipur&refine_results=Y&Refine_Localities=Refine%20Localities&action=%2Fdo%2Fquicksearch%2Fsearch&suggestion=CITY_75%2C%20PREFERENCE_R%2C%20RESCOM_R&searchform=1&price_max=null'
	]
	return start_urls[0]

# list_1=start()
# print list_1[:2]